# Site settings
title:       roobert
email:       roobert@gmail.com
author:      Rob Wilson
description: ""
baseurl:     ""
url:         "http://roobert.github.io"

gems:
  - jekyll-paginate
  # - jekyll-mermaid

# Google analytics
google_analytics: UA-56391015-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username: roobert
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# mermaid:
#   src: 'mermaid.min.js'

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     999
sass:
  compressed: true
